# gui:
#   theme:
#     selectedLineBgColor:
#       - reverse
#     selectedRangeBgColor:
#       - reverse
# git:
#   paging:
#     colorArg: always
#     useConfig: true
        # this would be nice but need to trouble shoot terrible performance issue        
        #git:
        #    paging:
        #        colorArg: always
        #        # pager: diff-so-fancy
        #        pager: delta --dark --paging=never --24-bit-color=always
