require("plugins")
require("mappings")
require("options")

--require "config.colorizer"
--require "config.nvim-reloader"
--require "config.nvim-gitsigns"
--require "config.nvim-comment"
--require('config.nvim-floaterm')
--require "config.nvim-matchup"
--require "config.nvim-lspkind"
--require "config.nvim-gitblame"
--require "config.nvim-lightbulb"
--require "config.nvim-indentline"
--require "config.nvim-multi-cursor"
---- require "config.nvim-tree"
--require "config.nvim-octo"
--require("config.nvim-statusline").setup()
--require("numb").setup()
--require("better_escape").setup()
---- require('nvim-autopairs').setup()
--require("which-key").setup()
----require('config.nvim-quickscope')
----require('config.nvim-numb')
----require('config.nvim-hop')
---- require("trouble").setup {}
--require("onedark").setup()
---- formatter
--require("formatter").setup {
--  filetype = {
--    lua = {
--      function()
--        return {
--          exe = "stylua",
--          args = {
--            "-",
--          },
--          stdin = true,
--        }
--      end,
--    },
--  },
--}
