--local helper = {}
--local api, cmd, fn, g = vim.api, vim.cmd, vim.fn, vim.g
--
--local function set_key_map(mode, lhs, rhs, opts)
--  local options = {noremap = false}
--  if opts then
--    options = vim.tbl_extend("force", options, opts)
--  end
--  api.nvim_set_keymap(mode, lhs, rhs, options)
--end
--
--function helper.map(lhs, rhs, opts)
--  return set_key_map("", lhs, rhs, opts)
--end
--
--function helper.imap(lhs, rhs, opts)
--  return set_key_map("i", lhs, rhs, opts)
--end
--
--function helper.nnoremap(lhs, rhs, opts)
--  return set_key_map("n", lhs, rhs, {noremap = true})
--end
--
--function helper.inoremap(lhs, rhs, opts)
--  return set_key_map("i", lhs, rhs, {noremap = true})
--end
--
--function helper.vnoremap(lhs, rhs, opts)
--  return set_key_map("v", lhs, rhs, {noremap = true})
--end
--
--function helper.tnoremap(lhs, rhs, opts)
--  return set_key_map("t", lhs, rhs, {noremap = true})
--end
--
--return helper
