require("hop").setup({ keys = "etovxqpdygfblzhckisuran" })
--require("hop").setup()
--vim.cmd("hi HopLine guifg=#ff007c gui=bold ctermfg=198 cterm=bold")
--local cmd = vim.cmd
--cmd [[highlight HopNextKey guifg=#ff5050 gui=bold,underline]]
--cmd [[highlight HopNextKey1 guifg=#ff5050 gui=bold,underline]]
--cmd [[highlight HopNextKey2 guifg=#ff5050 gui=bold,underline]]
--cmd [[highlight HopLine guifg=#ff5050 gui=bold,underline]]
-- vim.cmd("hi HopNextKey guifg=#ff9900")
-- vim.cmd("hi HopNextKey1 guifg=#ff9900")
-- vim.cmd("hi HopNextKey2 guifg=#ff9900")
