-- TODO: To be removed
-- local Terminal = require("toggleterm.terminal").Terminal
--
-- local M = {}
--
-- local lazygit = Terminal:new({
--   cmd = "lazygit",
--   hidden = true,
--   direction = "float",
--   close_on_exit = true,
--   dir = "git_dir",
--   float_opts = {
--     border = "curved",
--     width = 200,
--     height = 100,
--     winblend = 3,
--     highlights = {
--       border = "Normal",
--       background = "Normal",
--     },
--   },
-- })
--
-- M.lazygit_toggle = function()
--   lazygit:toggle()
-- end
--
-- local lf = Terminal:new({
--   cmd = "lf",
--   hidden = true,
--   direction = "float",
--   close_on_exit = true,
--   highlights = {
--     border = "Normal",
--     background = "Normal",
--   },
-- })
--
-- M.lf_toggle = function()
--   lf:toggle()
-- end
--
-- return M
--
--
-- -- require("toggleterm").setup({
-- --     size = function(term)
-- --         if term.direction == "horizontal" then
-- --             return 15
-- --         elseif term.direction == "vertical" then
-- --             return vim.o.columns * 0.4
-- --         end
-- --     end,
-- --     open_mapping = [[<c-t>]],
-- --     hide_numbers = true,
-- --     shade_filetypes = {},
-- --     shade_terminals = true,
-- --     -- shading_factor = 1,
-- --     direction = "float",
-- --     -- shell = 'flatpak-spawn --host --env=TERM="$TERM" zsh',
-- --     float_opts = {
-- --         border = "curved",
-- --         height = 20,
-- --         width = 100,
-- --     },
-- --     -- winblend = 20,
-- -- })
-- --
-- -- local Terminal  = require('toggleterm.terminal').Terminal
-- -- local lf = Terminal:new({ cmd = "lf", hidden = true })
-- -- function _lf_toggle()
-- --   lf:toggle()
-- -- end
-- -- vim.api.nvim_set_keymap("n", "<leader>L", "<cmd>lua _lf_toggle()<CR>", {noremap = true, silent = true})
